name: Terraform Validator

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .github/workflows/terraform.yaml
      - terraform/*.tf

permissions:
  contents: read

concurrency:
  group: terraform-${{ github.event.repository.name }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-24.04
    timeout-minutes: 20

    steps:
      - name: Check out repository
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          fetch-depth: 1
          persist-credentials: false

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@5e8dbf3c6d9deaf4193ca7a8fb23f2ac83bb6c85 # v4.0.0
        with:
          terraform_version: "1.15.2"
          terraform_wrapper: false

      - name: Validate Terraform
        run: make fmt-check init validate
